# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promedios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('viet', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='RiverRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('temperatura', models.CharField(max_length=10)),
                ('viento', models.CharField(max_length=30)),
                ('fuerza', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('contaminacion', models.CharField(max_length=30)),
            ],
        ),
    ]
